### ISSUE TITLE
Hide costs

### ISSUE THREAD

**Issue by dirkroorda** [Dans-labs/dariah#5]
In the overviews, hide the costs of contributions except the ones

* for which the user is national coordinator
* if the user is backoffice or more

**Comment by femmynine** [comment]
I believe we have touched upon this before, but it does not seem to be resolved yet: only NC's (user role: coord) and higher should be able to see the fields 'cost' and 'cost description'. These fields should be hidden to all other types of logged-in users. In addition, NC's should be able to see only the costs of their own country's contributions. I have already assigned all the NC's the coord role and added their particular country to their account.

**Comment by dirkroorda** [comment]
OK: Done. NC see the costs of contribs in their own country. They also see the aggregated costs of contribs in their own country. They do not see aggregated costs for contribs outside their country. Otherwise it becomes too easy to drill down to aggregations of only one contrib.
If NCs have not been assigned a country, they can see no more than an ordinary authenticated user.
