### ISSUE TITLE
Consolidation of records in the API

### ISSUE THREAD

**Issue by yoannspace** [Dans-labs/dariah#6]
Concerning our discussion today:

* Question:
Is there an API endpoint to retrieve all information of tools in english? Meaning I don’t get the information with identifiers like here: https://dariah-beta.dans.knaw.nl/api/db/view?table=contrib&id=000000001aca857b55000232 But I get everything already resolved.
For example, not “country”: “00000000e909c2d70600001a”
But instead “country”: “Austria” (found here: https://dariah-beta.dans.knaw.nl/api/db/view?table=country&id=00000000e909c2d70600001a)
it would be good to have something similar to retrieve all information of one contribution without having to send x requests to the API

* Possibility you provided:
Working on consolidation of records. Then you get all info of a contrib denormalized in one big json structure.
But that is slightly different. Yes maybe there should be a parameter saying: consolidated.

**Comment by dirkroorda** [comment]
I think the behaviour you describe should be the default behaviour, and the current behaviour should be triggered by a parameter like ?raw=true.

I'll work on it after consolidation (needed for pdf reporting) is finished.
